version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 5g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  postgres:
    build: ./docker
    container_name: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    mem_limit: 5g
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    links:
      - elasticsearch
